### ISSUE TITLE
Yarn error

### ISSUE THREAD

**Issue by luckyrsa** [mfrachet/create-frontend-framework#11]
Hi
I am getting these errors when trying to start a white page:
C:\FrontEnd\create-frontend-framework>yarn && yarn start
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
warning mini-css-extract-plugin@0.4.1: Invalid bin field for "mini-css-extract-plugin".
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "12.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.22.4
$ rm -rf .cache && rm -rf dist && parcel serve index.html
'rm' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

P.S. New to all this please assist

**Comment by mfrachet** [comment]
I've bumped some dependencies. You can re-clone the repo or pull master and retry your command 😄
